services:
  clojure:
    image: clojure:latest
    env_file: ".env-docker"
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
    working_dir: /usr/src/app
    ports:
      - 3010:3000
    entrypoint: >
      sh -c "clojure -J--enable-native-access=ALL-UNNAMED -M:run-m"

  redis:
      image: redis:7
    environment:
      TZ: Asia/Toky
    volumes:
      - data:/data

volumes:
  m2:
    external: true
  gitlibs:
    external: true
  data:
    driver: local
